apiVersion: v1
kind: Pod
metadata:
  name: locust
  namespace: bookshelf-namespace
spec:
  containers:
    - name: locust
      image: bookshelf-locust:1.0
      imagePullPolicy: Never
      command:
        - locust
        - -f
        - /mnt/locust/locustfile.py
        - --host
        - http://bookshelf-app-service:80