spring.application.name=bookshelf
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/bookshelf_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.freemarker.template-loader-path=classpath:/templates/

book.covers.path=D:/server/covers/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
