apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.database.appName }}-secret
  namespace: {{ include "bookshelf-chart.namespace" . }}
data:
  {{ .Values.global.database.databaseNameVariableName }}: {{ .Values.secret.postgresql.db | b64enc }}
  {{ .Values.global.database.databaseUserVariableName }}: {{ .Values.secret.postgresql.user | b64enc }}
  {{ .Values.global.database.databasePswVariableName }}: {{ .Values.secret.postgresql.password | b64enc }} 