apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: bookshelf-app
data:
  postgresql-db: "Ym9va3NoZWxmX2Ri" # bookshelf_db
  postgresql-user: "cG9zdGdyZXM=" # postgres
  postgresql-password: "cG9zdGdyZXM=" # postgres